version: "3"

services:
    ecoprodev:
        env_file:
             - path: ${PWD}/docker/.env
        build:
            context: ${PWD}/.
            dockerfile: ${PWD}/docker/Dockerfile
        volumes:
            - ${PWD}/scripts:/ecopro/scripts
            - ${ECOPRO_DATA_DIR}:/datafiles
            - ${ECOPRO_GEOSERVER_DATA_DIR}:/geoserver_data
