version: "3"

services:
    ecoprodev:
        build:
            context: ${PWD}/.
            dockerfile: ${PWD}/docker/Dockerfile
        networks:
            - ecopro_net
        volumes:
            - ${PWD}/scripts:/ecopro/scripts
            - ${PWD}/data_files:/datafiles

networks:
  ecopro_net:
    name: ecopro_network
    external: true
