version: "3"

services:
    backend:
        image: docker.osgeo.org/geoserver:2.24.x
        env_file:
             - path: ${PWD}/docker/.env
        networks:
            - ecopro_net
        expose:
            - 8080
        volumes:
            - ${ECOPRO_GEOSERVER_DATA_DIR}:/opt/geoserver_data:rw
        environment:
            - ROOT_WEBAPP_REDIRECT=true
            - PROXY_BASE_URL=https://ecopro-visualization.org/geoserver/
            - GEOSERVER_CSRF_WHITELIST=ecopro-visualization.org
            - INSTALL_EXTENSIONS=true
            - SKIP_DEMO_DATA=true
            - STABLE_EXTENSIONS=wps,netcdf,vectortiles,importer
            - COMMUNITY_EXTENSIONS=mbtiles-store,mbtiles,cog
            - CORS_ENABLED=true
    
    frontend:
        build: ${PWD}/common-mapping-client
        networks:
            - ecopro_net
        expose:
            - 8081
        volumes:
            - ${PWD}/nginx_logs:/var/log/nginx:rw

    proxy:
        image: caddy:2.7.6-alpine
        cap_add:
            - NET_ADMIN
        networks:
            - ecopro_net
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
            - ecopro_caddy_data:/data
            - ecopro_caddy_config:/config

networks:
  ecopro_net:
    name: ecopro_network
    driver: 'bridge'

volumes:
    ecopro_caddy_data:
        external: true
    ecopro_caddy_config:
            