version: "3"

services:
    backend:
        image: docker.osgeo.org/geoserver:2.24.x
        networks:
            - ecopro_net
        expose:
            - 8080
        volumes:
            - ${PWD}/geoserver_data:/opt/geoserver_data:rw
        environment:
            - ROOT_WEBAPP_REDIRECT=true
            - INSTALL_EXTENSIONS=true
            - SKIP_DEMO_DATA=true
            - STABLE_EXTENSIONS=netcdf,vectortiles,importer
            - COMMUNITY_EXTENSIONS=cog
            - CORS_ENABLED=true
        deploy:
            restart_policy:
                condition: on-failure
    
    frontend:
        build: ${PWD}/common-mapping-client
        networks:
            - ecopro_net
        expose:
            - 8081
        volumes:
            - ecopro_app:/usr/share/nginx/html/app:rw
            - ${PWD}/nginx_logs:/var/log/nginx:rw
        restart: always

    proxy:
        image: caddy:2.7.6-alpine
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        networks:
            - ecopro_net
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
            - ecopro_caddy_data:/data
            - ecopro_caddy_config:/config

networks:
  ecopro_net:
    name: ecopro_network
    driver: 'bridge'

volumes:
    ecopro_app:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PWD}/common-mapping-client_build
    ecopro_caddy_data:
        external: true
    ecopro_caddy_config:
            